# Generated by Django 3.0.8 on 2020-07-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200717_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
